version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: nhn-eat-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nhn-eat-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-prootpassword",
        ]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

  backend:
    build: ./back-spring
    container_name: nhn-eat-backend
    image: leesang2/nm-eat
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - nhn-eat-network

  nginx:
    image: nginx:alpine
    container_name: nhn-eat-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - backend
    networks:
      - nhn-eat-network

volumes:
  mysql_data:

networks:
  nhn-eat-network:
    driver: bridge
